### ISSUE TITLE
SCSS dependency?

### ISSUE THREAD

**Issue by am80l** [Yelp/lemon-reset#27]
It looks like scss compiler is needed for this to run, but it isn't called out anywhere as a dependency. It's a little odd to me that it uses scss under the hood as opposed to just using the compiled CSS, maybe there is a good reason for that. It would be nice if the depency could be removed. If not, a simple note in the description with an example webpack config using SCSS loader would be appreciated.

**Comment by adityavohra7** [comment]
@am80l thanks for opening the issue!

We use `sass-loader` internally at Yelp, but there's no real need for this repo to expect its consumers to also use it. We can totally have the exported components import CSS directly. There would still be an implicit dep on `css-loader` I think? We can improve the documentation around that though. Feel free to send a PR our way if you need the changes sooner rather than later!

**Comment by am80l** [comment]
Cool thats what I was thinking as well. We use Post-CSS so the SCSS requirement caught me a little off-guard. The css-loader will still be a dependency, but that is mostly expected. A short snippet in docs would suffice. 

I will say though, having played with this project a bit today, this is really awesome work you guys at Yelp have contributed. I work on a team that builds components for a large software company with many product ecosystems. CSS issues due to different resets etc being used across properties is a constant pain point for us. So thank you for opening this up, I can see this preventing a lot of issues for us once we start using it in production.

**Comment by adityavohra7** [comment]
@am80l thank you! We're super glad you like our project 😊🎉
